version: '3'
services:
  db:
    build:
      context: docker/db
    ports:
      - "15432:5432"
    restart: always
    volumes:
      - "pg_data:/var/lib/postgresql/data"
  app:
    build:
      context: .
      dockerfile: docker/devday/Dockerfile
    ports:
      - "8000:8000"
      - "18080:7000"
    depends_on:
      - db
    volumes:
      - "./devday:/srv/devday/devday"
      - "devday_media:/srv/devday/devday/media"
      - "devday_static:/srv/devday/devday/static"
  revproxy:
    build:
      context: docker/revproxy
    ports:
      - "8080:80"
    depends_on:
      - app
    volumes:
      - "devday_media:/usr/local/apache2/htdocs/media"
      - "devday_static:/usr/local/apache2/htdocs/static"

volumes:
  devday_media:
  devday_static:
  pg_data:
