version: '3'
services:
  vault:
    image: vault:0.11.1
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: devday_root
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    command: "server -dev"
  app:
    environment:
      VAULT_URL: http://vault:8200
      VAULT_TOKEN: devday_root
      DJANGO_SETTINGS_MODULE: devday.settings.dev
