version: '3'
services:
  db:
    build:
      context: docker/db
    ports:
      - "15432:5432"
    restart: always
    volumes:
      - "pg_data:/var/lib/postgresql/data"
  vault:
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
  app:
    depends_on:
      - db
      - vault
    volumes:
      - "./devday:/srv/devday/devday"
      - "devday_media:/srv/devday/devday/media"
      - "devday_static:/srv/devday/devday/static"

volumes:
  devday_media:
  devday_static:
  pg_data:
