version: '3'
services:
  db:
    image: ${DOCKER_HUB_USERNAME}devday-website-db:prod
    build:
      dockerfile: Dockerfile-prod
    env_file:
      prod-env-db
  vault:
    image: ${DOCKER_HUB_USERNAME}devday-website-vault:prod
    build:
      context: docker/vault
    volumes:
      - "vaultlogs:/vault/logs"
      - "vaultfile:/vault/file"
    command: server
  mail:
    image: ${DOCKER_HUB_USERNAME}devday-website-mail:prod
    build:
      context: docker/mail
      args:
        http_proxy: ${http_proxy}
        no_proxy: ${no_proxy},vault
    env_file:
      prod-env-mail
  app:
    # Tag image as prod to distinguish from dev
    image: ${DOCKER_HUB_USERNAME}devday-website-app:prod
    build:
      context: .
      dockerfile: docker/app/Dockerfile-prod
      args:
        http_proxy: ${http_proxy}
        no_proxy: ${no_proxy},vault
    environment:
      VAULT_URL: https://vault:8200
      DJANGO_SETTINGS_MODULE: devday.settings.prod
    env_file:
      prod-env
    volumes:
      - "devday_media:/srv/devday/media"
      - "devday_static:/srv/devday/static"
      - "devday_logs:/srv/devday/logs"
    depends_on:
      - db
      - vault
      - mail
  revproxy:
    image: ${DOCKER_HUB_USERNAME}devday-website-revproxy:prod
    build:
      context: docker/revproxy
    ports:
      - "8080:80"
      - "80:80"
    depends_on:
      - app
    volumes:
      - "devday_media:/usr/local/apache2/htdocs/media"
      - "devday_static:/usr/local/apache2/htdocs/static"

volumes:
  vaultlogs:
  vaultfile:
  devday_logs:
