version: '3'
services:
  db:
    ports:
      - "15432:5432"
  vault:
    image: vault:0.11.1
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: devday_root
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    command: "server -dev"
  app:
    # tag dev image as devday_hp_app_dev
    image: devday_hp_app:dev
    build:
      context: .
      dockerfile: docker/app/Dockerfile-dev
      args:
        http_proxy: ${http_proxy}
        no_proxy: ${no_proxy},vault
    ports:
      - "8000:8000"
    environment:
      VAULT_URL: http://vault:8200
      VAULT_TOKEN: devday_root
      DJANGO_SETTINGS_MODULE: devday.settings.dev
    volumes:
      - "./devday:/srv/devday/devday"
      - "devday_media:/srv/devday/devday/media"
      - "devday_static:/srv/devday/devday/static"
