version: '3'
services:
  db:
    image: ${DOCKER_REGISTRY}devday-website-db:dev
    restart: "no"
    ports:
      - "15432:5432"
  vault:
    image: vault:0.11.1
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: devday_root
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    command: "server -dev"
  app:
    # Tag image as dev to distinguish from prod
    image: ${DOCKER_REGISTRY}devday-website-app:dev
    build:
      context: .
      dockerfile: docker/app/Dockerfile-dev
      args:
        http_proxy: ${http_proxy}
        no_proxy: ${no_proxy},vault
    ports:
      - "8000:8000"
    environment:
      VAULT_URL: http://vault:8200
      VAULT_TOKEN: devday_root
      DJANGO_SETTINGS_MODULE: devday.settings.dev
    volumes:
      - "devday_media:/srv/devday/media"
      - "devday_static:/srv/devday/static"
      - "./devday:/srv/devday"
